# Generated by Django 5.0.1 on 2025-06-22 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='current_step',
            field=models.IntegerField(default=1, help_text='Текущий шаг диалога'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='is_multi_step',
            field=models.BooleanField(default=False, help_text='Многошаговый диалог'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='max_steps',
            field=models.IntegerField(default=3, help_text='Максимальное количество шагов'),
        ),
        migrations.AddField(
            model_name='message',
            name='step_number',
            field=models.IntegerField(default=1, help_text='Номер шага, на котором отправлено сообщение'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_multi_step',
            field=models.BooleanField(default=False, help_text='Диалог с несколькими шагами'),
        ),
        migrations.AddField(
            model_name='question',
            name='max_steps',
            field=models.IntegerField(default=3, help_text='Максимальное количество шагов в диалоге'),
        ),
        migrations.CreateModel(
            name='DialogStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(help_text='Номер шага в диалоге')),
                ('trigger_keywords', models.TextField(help_text='Ключевые слова для активации этого шага (через запятую)')),
                ('client_message', models.TextField(help_text='Сообщение клиента на этом шаге')),
                ('expected_operator_response', models.TextField(blank=True, help_text='Ожидаемый ответ оператора (для проверки)')),
                ('client_follow_up', models.TextField(blank=True, help_text='Дополнительное сообщение клиента после ответа оператора')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_steps', to='chat.question')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('question', 'step_number')},
            },
        ),
    ]
