# Generated by Django 5.0.1 on 2025-06-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_dialog_current_step_dialog_is_multi_step_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='max_steps',
        ),
        migrations.RemoveField(
            model_name='message',
            name='step_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_multi_step',
        ),
        migrations.AddField(
            model_name='dialog',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='chat.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='stop_words',
            field=models.CharField(blank=True, help_text='Стоп-слова для завершения диалога, через запятую', max_length=255),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='current_step',
            field=models.IntegerField(default=1, help_text='Текущий шаг в многошаговом диалоге'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='is_multi_step',
            field=models.BooleanField(default=False, help_text='Это многошаговый диалог?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_steps',
            field=models.IntegerField(default=1, help_text='Количество шагов в этом вопросе (для многошаговых диалогов)'),
        ),
        migrations.DeleteModel(
            name='DialogStep',
        ),
    ]
