# Generated by Django 5.0.1 on 2025-06-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_dialog_max_steps_remove_message_step_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_multi_step',
            field=models.BooleanField(default=False, help_text='Активируйте, если у вопроса несколько шагов', verbose_name='Многошаговый'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_steps',
            field=models.IntegerField(default=1, help_text='Количество шагов в этом вопросе (для многошаговых диалогов)', verbose_name='Макс. шагов'),
        ),
    ]
