# Generated by Django 5.0.1 on 2025-06-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_question_is_multi_step_alter_question_max_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Номер шага')),
                ('trigger_keywords', models.TextField(blank=True, help_text='Ключевые слова клиента для этого шага (через запятую).', verbose_name='Триггерные слова')),
                ('client_message', models.TextField(help_text='Точное сообщение, которое отправит клиент на этом шаге.', verbose_name='Сообщение клиента')),
                ('expected_operator_response', models.TextField(blank=True, help_text='Правильный ответ, который должен дать оператор.', verbose_name='Ожидаемый ответ оператора')),
                ('response_variation', models.TextField(blank=True, help_text='Допустимые вариации ответа оператора (через точку с запятой).', verbose_name='Вариации ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='chat.question')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('question', 'step_number')},
            },
        ),
    ]
